[workspace]
members = [
    "darklight_driver/", "dl_instance",
    "dlwp/",
    "test_streams/test_client",
    "test_streams/test_server",
    "tools/dlcmd", 
    "tools/dlcns",
    "tools/dlup",
    "tools/new_dlukey/",
]
