[package]
name = "dlcns"
version = "0.1.0"
edition = "2021"

[dependencies]
dlwp = { path = "../../dlwp/", features = ["include_serde"] }
serde = { version = "1.0.188", features = ["serde_derive", "std"] }
